USE Community

CREATE TABLE Users
(
  UserID INT IDENTITY(1,1) PRIMARY KEY,
  Username NVARCHAR(50) NOT NULL,
  Fname NVARCHAR(50) NOT NULL,
  Lname NVARCHAR(50) NOT NULL,
  Address NVARCHAR(255) NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  Email NVARCHAR(100) NOT NULL
);
USE Community
CREATE TABLE Requests
(
  RequestID INT IDENTITY(1,1) PRIMARY KEY,
  UserID INT NOT NULL,
  Category NVARCHAR(50) NOT NULL,
  RequestName NVARCHAR(50) NOT NULL,
  Description NVARCHAR(255) NOT NULL,
  Location NVARCHAR(255) NOT NULL,
  Status NVARCHAR(50) NOT NULL,
  Date DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_Requests_Users FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

USE Community
CREATE TABLE Offers
(
  OfferID INT IDENTITY(1,1) PRIMARY KEY,
  UserID INT NOT NULL,
  Category NVARCHAR(50) NOT NULL,
  OfferName NVARCHAR(50) NOT NULL,
  Description NVARCHAR(255) NOT NULL,
  Location NVARCHAR(255) NOT NULL,
  Status NVARCHAR(50) NOT NULL,
  Date DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_Offers_Users FOREIGN KEY (UserID) REFERENCES Users(UserID),
);

USE Community
CREATE TABLE Messages
(
  MessageID INT IDENTITY(1,1) PRIMARY KEY,
  SenderID INT NOT NULL,
  ReceiverID INT NOT NULL,
  MessageTEXT NVARCHAR(MAX) NOT NULL,
  TIMESTAMP DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_Messages_Sender FOREIGN KEY (SenderID) REFERENCES Users(UserID),
  CONSTRAINT FK_Messages_Receiver FOREIGN KEY (ReceiverID) REFERENCES Users(UserID)
)

USE Community
CREATE TABLE Reviews
(
  ReviewID INT IDENTITY(1,1) PRIMARY KEY,
  ReviewerID INT NOT NULL,
  RevieweeID INT NOT NULL,
  Rating INT NOT NULL,
  ReviewText NVARCHAR(500),
  TIMESTAMP DATETIME DEFAULT GETDATE(),
  CONSTRAINT FK_Reviews_Reviewer FOREIGN KEY (ReviewerID) REFERENCES Users(UserID),
  CONSTRAINT FK_Reviews_Reviewee FOREIGN KEY (RevieweeID) REFERENCES Users(UserID),
  CONSTRAINT CHK_Rating CHECK (Rating >= 1 AND Rating <= 5)
);
USE Community

ALTER TABLE Users
ADD ProfileImageURL VARCHAR(255);




